name: Build Aseprite for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.10

    - name: Install dependencies
      run: |
        choco install --yes git
        choco install --yes gtksharp
        choco install --yes mingw

    - name: Build Aseprite
      run: |
        mkdir build
        cd build
        cmake .. -G "MinGW Makefiles"
        mingw32-make aseprite

    - name: Package Aseprite
      run: |
        mkdir -p aseprite-bin
        copy /Y bin/Release/aseprite.exe aseprite-bin/aseprite.exe

    - name: Upload Aseprite Executable
      uses: actions/upload-artifact@v4
      with:
        name: aseprite
        path: aseprite-bin/aseprite.exe
