name: Buid Aseprite for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Chocolatey
      win_setup: choco install -y

    - name: Install Dependencies
      run: |
        choco install -y cmake git mingw
        choco install -y freetype harfbuzz
        choco install -y lua
        choco install -y pkgconfiglite

    - name: Setup Environment Variables
      run: |
        echo "PATH=$PATH:C:\Program Files\mingw\bin" >> $GITHUB_ENV

    - name: Configure Aseprite
      run: |
        mkdir build
        cd build
        cmake -G "MinGW Makefiles" -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=../aseprite_install ..

    - name: Build Aseprite
      run: |
        cd build
        mingw32-make aseprite

    - name: Install Aseprite
      run: |
        cd build
        mingw32-make install

    - name: Upload Aseprite Build
      uses: actions/upload-artifact@v2
      with:
        name: aseprite-windows
        path: aseprite_install/bin/aseprite.exe
