name: Build Aseprite for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v1.1.0

    - name: Install dependencies
      run: |
        nuget restore aseprite.sln

    - name: Build Aseprite
      run: |
        msbuild aseprite.sln /p:Configuration=Release /p:Platform=x64

    - name: Package Aseprite
      run: |
        mkdir -p aseprite-bin
        copy /Y bin\Release\aseprite.exe aseprite-bin\aseprite.exe

    - name: Upload Aseprite Executable
      uses: actions/upload-artifact@v4
      with:
        name: aseprite
        path: aseprite-bin\aseprite.exe
