name: Build Aseprite for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    name: Build Aseprite for Android
    runs-on: ubuntu-latest

    steps:
      # Etapa 1: Checar o código-fonte
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Etapa 2: Configurar o ambiente do NDK para Android
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30  # Defina o nível da API que você deseja usar
          build-tools: "30.0.3"
          ndk: "21.4.7075529"  # Versão do NDK necessária para compilar o código C++

      # Etapa 3: Instalar dependências de build como CMake e ninja
      - name: Install CMake and Ninja
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build

      # Etapa 4: Baixar dependências do Aseprite (Skia, Freetype etc.)
      - name: Download Aseprite dependencies
        run: |
          git clone --recursive https://github.com/aseprite/aseprite.git
          cd aseprite
          mkdir build
          cd build

      # Etapa 5: Configurar o projeto com CMake para o Android NDK
      - name: Configure CMake for Android NDK
        run: |
          cmake \
            -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=armeabi-v7a \
            -DANDROID_PLATFORM=android-30 \
            -DCMAKE_BUILD_TYPE=Release \
            -DSKIA_DIR=../third_party/skia \
            -DSKIA_LIBRARY_DIR=../third_party/skia/out/Release \
            -DSKIA_INCLUDE_DIR=../third_party/skia/include \
            ..

      # Etapa 6: Compilar o projeto
      - name: Build Aseprite for Android
        run: |
          cmake --build . --target aseprite

      # Etapa 7: Carregar os binários/artefatos compilados
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Aseprite Android APK
          path: build/aseprite.apk
